# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tokenizer.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'tokenizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftokenizer.proto\x12\ttokenizer\"G\n\x0cTokenRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x15\n\rprompt_tokens\x18\x03 \x03(\t\"$\n\x11TokenRequestReply\x12\x0f\n\x07message\x18\x01 \x01(\t2R\n\tTokenizer\x12\x45\n\nSendTokens\x12\x17.tokenizer.TokenRequest\x1a\x1c.tokenizer.TokenRequestReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tokenizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENREQUEST']._serialized_start=30
  _globals['_TOKENREQUEST']._serialized_end=101
  _globals['_TOKENREQUESTREPLY']._serialized_start=103
  _globals['_TOKENREQUESTREPLY']._serialized_end=139
  _globals['_TOKENIZER']._serialized_start=141
  _globals['_TOKENIZER']._serialized_end=223
# @@protoc_insertion_point(module_scope)
